# Generated by Django 6.0.3 on 2026-04-04 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_saved_posts'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='theme_preference',
        ),
    ]
