# Generated by Django 6.0.3 on 2026-05-03 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0005_remove_message_attachment_messageattachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='deleted_by_receiver',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='message',
            name='deleted_by_sender',
            field=models.BooleanField(default=False),
        ),
    ]
