# Generated by Django 6.0.3 on 2026-05-02 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_tools', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='aiprovidersettings',
            name='ai_model',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
