# Generated by Django 6.0.3 on 2026-04-28 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0003_studygroup_access_type_studygroup_group_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='groupmessage',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='group_messages/'),
        ),
    ]
